title: Snowjam's AI Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  email: snowjam02@gmail.com
  github: SupunKavinda

baseurl: "" 
url: "https://snowjamai.github.io/" 
plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N